# Generated by Django 4.2.11 on 2024-04-05 18:17

import MuziqLyrics.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muziquser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='muziquser',
            managers=[
                ('object', MuziqLyrics.accounts.managers.MuziqUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='muziquser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='muziquser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='muziquser',
            name='last_name',
        ),
    ]
