# Generated by Django 4.2.11 on 2024-04-05 18:20

import MuziqLyrics.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_muziquser_options_alter_muziquser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='muziquser',
            managers=[
                ('objects', MuziqLyrics.accounts.managers.MuziqUserManager()),
            ],
        ),
    ]
