# Generated by Django 4.2.11 on 2024-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_muziquser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='muziquser',
            name='AccountType',
            field=models.CharField(choices=[('Listener', 'Listener'), ('Artist', 'Artist')], default='Listener', max_length=20),
        ),
    ]
