# Generated by Django 4.2.11 on 2024-04-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_muziquser_accounttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muziquser',
            old_name='AccountType',
            new_name='account_type',
        ),
    ]
