# Generated by Django 4.2.11 on 2024-04-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lyrics', models.TextField()),
                ('release_date', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Classical', 'Classical'), ('Jazz', 'Jazz'), ('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Country', 'Country'), ('Electronic', 'Electronic')], max_length=20)),
                ('cover_image', models.URLField(default='https://gibus.be/wp-content/uploads/woocommerce-placeholder-1000x1000.png')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
                ('artists', models.ManyToManyField(to='artists.artist')),
            ],
        ),
    ]
