# Generated by Django 4.2.11 on 2024-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.URLField(default='https://buffer.com/library/content/images/size/w1200/2023/10/free-images.jpg'),
        ),
    ]
